### ISSUE TITLE
Fawe issue with WE in own world

### ISSUE THREAD

**Issue by Sckaletz** [Butzlabben/worldsystem#43]
I'm using Fawe and my players aren't able to use worldedit in their worlds, due to the fact that they are missing the permission fawe.admin. So I decided to create a command in the settings file that would grant them that permission in their world.
That can't be done with Luckperms since the world is saved as that loooong uuid number. This is what it says:

Server/world names can only contain alphanumeric characters and cannot exceed 36 characters in lenght.

So how do I grant players permission to use worldedit in their own world? I can't just give them fawe.admin in general as that would make them able to use it anywhere else.

**Comment by Butzlabben** [comment]
As this is a well known issue, you can expect a bug fix.

**Comment by VozikCZE** [comment]
@Butzlabben Lets fix it?

**Comment by Butzlabben** [comment]
I think that the newest commits should fix this issue. Testing still has to be done

**Comment by VozikCZE** [comment]
I tested it, but it still doesn't work without admin permission.

**Comment by Xaver106** [comment]
Same issue in #58 I commented a possible fix in there
